apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i05ugy0z8-java-springboot
  janus-idp.io/tekton: i05ugy0z8-java-springboot
  backstage.io/kubernetes-id: i05ugy0z8-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i05ugy0z8-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
